# This file defines a custom launcher named 'my_cluster'.
# It inherits the base configuration from the 'submitit_slurm' launcher
# and overrides it with settings specific to your SLURM environment.
defaults:
  - submitit_slurm

# Explicitly set the target class for the launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# Your cluster-specific SLURM parameters
timeout_min: 60
nodes: 1
tasks_per_node: 1
cpus_per_task: 12
mem_gb: 64
gres: "gpu:4" # Using gres directly as in the example
constraint: "gpu80"
name: ${hydra.job.name}
# Enable automatic resubmission on timeout (will resubmit up to 10 times)
max_num_timeout: 10
setup:
  - "source /scratch/gpfs/ashwinee/new/activate.sh" 