# @package _global_
# Distributed LVAE training configuration for Hydra

# Training mode
training_mode: lvae_bart

# evaluate model
is_eval: false

# Model configuration
model:
  vocab_size: 50257
  d_model: 768
  latent_dim: 1536
  num_latents: 8
  dim_head: 128
  max_seq_len: 128
  num_layers: 12
  tokenizer_name: "gpt2"

# Training configuration
train_num_steps: 100000
train_bs: 128
eval_bs: 128
eval_every: 200
grad_accumulate: 2
compile_model: true
resume_from: null
results_folder: null

freeze_bb: true

# parallelization config
fsdp: false

# Data configuration
# train_bin_pattern: "/p/vast1/pretrain/datasets/diffusion/fineweb100B/fineweb_train_*.bin"
# val_bin_pattern: "/p/vast1/pretrain/datasets/diffusion/fineweb100B/fineweb_val_*.bin"
train_bin_pattern: "/p/vast1/madan2/diffusion-root/ldlm/dataset_util/tin_stories_bart_bin/tiny_train_*.bin"
val_bin_pattern: "/p/vast1/madan2/diffusion-root/ldlm/dataset_util/tin_stories_bart_bin/tiny_validation_*.bin"

total_tokens: 100000000000  # 100B tokens

# Optimization configuration
learning_rate: 8e-5
adam_betas: [0.9, 0.95]  # Changed from separate adam_beta1/adam_beta2 to tuple
adam_weight_decay: 0.1
adam_eps: 1e-9
muon_lr: 2e-2
muon_momentum: 0.95

adam_only: false

# VAE configuration
kld_weight: 0.0
kld_annealing_steps: 5000
use_precomputed_latents: False

# Logging configuration
seed: 42
log_step_interval: 1
output_dir: "outputs_killian"
wandb_name: "lvae-distributed"
wandb_mode: "online"
save_checkpoint: true

# Cluster shenanigans
per_process_vram_ratio: 0.8  # eg. 0.8, For APUs like MI300A and GH200

# Resume configuration (optional)
# resume_from: "outputs/model_best.pt"

# Hydra configuration
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false 